### ISSUE TITLE
[FEATURE] Remove Bitwarden CLI dependency

### ISSUE THREAD

**Issue by maxirus** [maxlaverse/terraform-provider-bitwarden#26] opened 2022-05-27 16:47 UTC
Any plans to remove the Bitwarden CLI dependency and allowing the provider to work without 3rd party tools?

**Comment by maxlaverse** [comment] 2022-05-30 18:17
Hi @maxirus !
No serious plans to be honest.

I spent  some time working on a partial Go implementation of the Bitwarden CLI because I needed it for testing:
https://github.com/maxlaverse/terraform-provider-bitwarden/tree/main/internal/bitwarden/webapi

There are quite a few cryptographic parameters and initialization processes required, and they most likely have to be done right in order to keep people's Vaults safe. I wouldn't have enough time to spend, to bring such an implementation in a state where I would feel confident people can safely use it.

**Comment by wscourge** [comment] 2022-06-21 06:18
The lack of this feature mean that it won't work with Terraform Cloud as a backend, right? It'll result in:

> Error: exec: "bw": executable file not found in $PATH

Just making sure I understand that correctly.

**Comment by maxlaverse** [comment] 2022-06-22 20:38
Good question @wscourge !
I think I read that Terraform Cloud allows you to host the runners when you have a business license, which likely opens the possibility to customize their environments. and add the Bitwarden CLI.

I wouldn't know how to run it on Terraform Cloud's free plan right now. I had a quick look in the developer documentation, searching for something that would hint at how to handle external tools, and found nothing. Looking into the Terraform projects I have, it seems all their providers are a single binary using Go SDKs to access external services.

**Comment by maxlaverse** [comment] 2022-06-25 12:20
Have you tried a combination of `null_resource` and `provisioner "local-exec" {}` @wscourge ?

**Comment by wscourge** [comment] 2022-09-22 07:35
I haven't, just opted-out of the TF Cloud for various reasons.  I guess it could work tho, definitely worth trying by anyone who ends up here.

**Comment by larivierec** [comment] 2023-07-15 00:56
While I do agree that the dependency should be removed as it removes the ability to use this in GitOps tools like tf-runner/tf-controller.

I recently tried integrating this and stumped onto the issue.
I think the issue here is without the CLI, the RestAPI is not exposed and therefore, we can't interact with our Vaults.

[cloudflare](https://github.com/larivierec/home-cluster/blob/main/infrastructure/terraform/cloudflare/provider.tf#L34-L39)

Do you think instead adding support for self-hosting the bitwarden-cli elsewhere and using that URL without credentials could be an alternative?

Is it possible to create a second `provider` that wouldn't require downloading of bw-cli?

```hcl
provider "bitwarden" {
  internal_api          = "https://bitwarden-cli.bitwarden.svc.cluster.local.:8087"
}
```

along side the standard ones that are already available in this project?

**Comment by larivierec** [comment] 2023-07-18 14:42
Yeah, for point 1, it can be scary but it's the responsible of the one deploying to keep the vault safe. I do agree that it can be.
point 2: ok ✅ 

point 3: 
i tried that, the issue is that tf-runner uses alpine. i tried quite hard to get bw cli running on alpine there's always dependency problems. the closest i got was a segmentation fault. this would also be my preferred option by creating a new alpine image and adding all the proper dependencies from both but alpine and bw seem to be a no go.

also, this is also my preferred solution 💯 

https://github.com/larivierec/containers/blob/main/apps/tf-runner-bw/Dockerfile

if you have any ideas, let me know

i also tried

```dockerfile
FROM alpine:3.18

WORKDIR /usr/local/bin
RUN apk update && apk add curl unzip jq

RUN export VER=$(curl -H "Accept: application/vnd.github+json" https://api.github.com/repos/bitwarden/clients/releases | jq  -r 'sort_by(.published_at) | reverse | .[].name | select( index("CLI") )' | sed 's:.*CLI v::' | head -n 1) && \
curl -LO "https://github.com/bitwarden/clients/releases/download/cli-v{$VER}/bw-linux-{$VER}.zip" \
&& unzip *.zip && chmod +x ./bw && rm *.zip

# ATTEMPT #1 

RUN apk add --no-cache libc6-compat \
&& apk add --no-cache gcompat=1.1.0-r1 \
&& apk add --no-cache libstdc++=12.2.1_git20220924-r10 \
&& rm -rf /var/cache/apk/*

# ATTEMPT #2

# RUN export GLIBC_VERSION=2.35-r1 && export GLIBC_REPO=https://github.com/sgerrand/alpine-pkg-glibc && \
#   apk --update add libstdc++ curl ca-certificates && \
#   for pkg in glibc-${GLIBC_VERSION} glibc-bin-${GLIBC_VERSION}; \
#      do curl -sSL ${GLIBC_REPO}/releases/download/${GLIBC_VERSION}/${pkg}.apk -o /tmp/${pkg}.apk; done && \
#   apk add --allow-untrusted /tmp/*.apk && \
#   rm -v /tmp/*.apk


COPY entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by larivierec** [comment] 2023-07-18 22:06
I didn't try it that way around I assumed it couldn't be done. Probably an error on my part!

Ill try and see how it pans out :)

**Comment by studiofrancium** [comment] 2024-01-17 09:48
For an idea, Spacelift free tier allows you to specify a custom Docker runner image - see [here](https://docs.spacelift.io/integrations/docker#allowed-registries-on-public-worker-pools).

[Dockerfile](https://github.com/spacelift-io/runner-terraform)

**Comment by maxlaverse** [comment] 2024-09-29 20:22
Hi! I've implemented experimental support for using the provider without requiring the Bitwarden CLI to be installed. If you have the opportunity, please give it a try! I appreciate any feedback.

**Comment by larivierec** [comment] 2024-09-30 23:14
Awesome, this is a great step up. 
I tried the last 2 versions.

The first 9.0, just crash dumped.
This one, 9.1 has this output

```bash
│ Error: error login with api key: bad response status code for 'https://vault.bitwarden.com/identity/connect/token': 400!=200, body:{"error":"invalid_grant","ErrorModel":{"Message":"No device information provided.","Object":"error"}}
```

**Comment by maxlaverse** [comment] 2024-10-01 16:45
Should be fixed in 0.9.2

**Comment by larivierec** [comment] 2024-10-01 17:01
No problem, I wish i could supply direct chat, but maybe better like this.
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: error decrypting account secrets: unsupported kdf type '1'
│
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 34, in provider "bitwarden":
│   34: provider "bitwarden" {
```

new error.

**Comment by maxlaverse** [comment] 2024-10-01 19:09
Alright, I had heard about discussion to introduced new KDF algorithms. I didn't know it went through, and you seem to be using it. I've added support for it in 0.9.3, hope it works for you as well.

**Comment by larivierec** [comment] 2024-10-01 19:20
yeah, actually, it's setup in my vault.

I wonder if these should be parameters or inferred, if that's even possible.

<img width="805" alt="image" src="https://github.com/user-attachments/assets/84df860b-3587-4b4d-8c19-a02a95a0f36c">

here's the trace.

```bash
│ Error: Plugin did not respond
│
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on provider.tf line 34, in provider "bitwarden":
│   34: provider "bitwarden" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-bitwarden_v0.9.3 plugin:

panic: argon2: parallelism degree too low

goroutine 23 [running]:
golang.org/x/crypto/argon2.deriveKey(0x0?, {0x14000417360?, 0x0?, 0x14000048b78?}, {0x140000382a0?, 0x140004b4cf8?, 0x10?}, {0x0?, 0x102f84204?, 0x0?}, ...)
	golang.org/x/crypto@v0.27.0/argon2/argon2.go:105 +0x198
golang.org/x/crypto/argon2.IDKey(...)
	golang.org/x/crypto@v0.27.0/argon2/argon2.go:97
github.com/maxlaverse/terraform-provider-bitwarden/internal/bitwarden/crypto/keybuilder.buildKey({0x140000d4070, 0xe}, {0x1400039a3c0, 0x16}, {0x1400007c5a0?, 0x0?, 0x14000048f48?, 0x1035d9980?})
	github.com/maxlaverse/terraform-provider-bitwarden/internal/bitwarden/crypto/keybuilder/prelogin_key.go:24 +0x118
```

**Comment by maxlaverse** [comment] 2024-10-02 08:19
I released 0.9.4, prevented the provider from crashing on low Argon2 parallelism, fixed why it was low and added more tests with Argon2 + User/Password auth 🤞

**Comment by larivierec** [comment] 2024-10-02 12:43
Great, 0.9.4 seems to work great for me with cloud vault.
Thank you 👍

**Comment by maxlaverse** [comment] 2024-10-02 14:29
Glad to hear! Let's do this then, and if you face any problem don't hesitate to create a new issue.

**Closed by maxlaverse** 2024-10-02 14:29 UTC
Labels: enhancement

**Comment by larivierec** [comment] 2024-10-02 17:05
The only thing that I find weird is that when it runs I get an email saying

**New Device Logged In From Firefox**

It would be cool if it said tf provider bw 

But this is nitpicking :)

**Comment by maxlaverse** [comment] 2024-10-02 19:00
Good point. There is a finite list of _device types_ to chose from: https://github.com/bitwarden/server/blob/main/src/Core/Enums/DeviceType.cs

A lot of them are _operating-system-specific_. Else there is "Unknown Browser", "UWP", "Server" or "SDK" left. I think the latter is probably what makes most sense. I would push this on `main` and release it with other fixes / improvements.

**Comment by larivierec** [comment] 2024-10-02 19:36
> Good point. There is a finite list of _device types_ to chose from: https://github.com/bitwarden/server/blob/main/src/Core/Enums/DeviceType.cs
> 
> 
> 
> A lot of them are _operating-system-specific_. Else there is "Unknown Browser", "UWP", "Server" or "SDK" left. I think the latter is probably what makes most sense. I would push this on `main` and release it with other fixes / improvements.

Yup, SDK is the best choice :)
