### ISSUE TITLE
[Feature request] Support Bitwarden SSO/BW_SESSION environment variable

### ISSUE THREAD

**Issue by pa-jberanek** [maxlaverse/terraform-provider-bitwarden#42] opened 2022-08-12 12:43 UTC
Hi there,

### Terraform Version
n/a

### Affected Resource(s)
General login/usage of bw CLI

### Terraform Configuration Files
n/a

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Support logging in to Bitwarden CLI with "bw login --sso" and then utilisation of the BW_SESSION environment variable inside the provider, rather than expecting to perform the whole login inside the provider - which won't work with SSO login.

### Actual Behavior
As far as I can tell from documentation and the source code, this method of using Bitwarden does not seem to be supported.

### Steps to Reproduce
n/a

### Important Factoids
n/a

### References
n/a

**Comment by maxlaverse** [comment] 2022-08-13 11:00
Hi @pa-jberanek !
Thanks for your input. That feature sounds reasonable and I'll try to implement it this month if nobody has by then.

**Comment by pa-jberanek** [comment] 2022-08-19 14:38
> Hi @pa-jberanek ! Thanks for your input. That feature sounds reasonable and I'll try to implement it this month if nobody has by then.

Thanks for looking at my request. 👍

**Comment by maxlaverse** [comment] 2022-08-20 11:00
I thought about it again @pa-jberanek. I'm trying to better understand how the provider is used.

Wouldn't [API Credentials](https://registry.terraform.io/providers/maxlaverse/bitwarden/latest/docs#api-credentials) work to interact with your Vault despite it relying on SSO ?

**Comment by pa-jberanek** [comment] 2022-08-22 13:40
The problems with that are:
* We'd not want every person who uses a Terraform stack with Bitwarden provider usage to have access to an API key, really
* We can't supply a password as shown in that, as with SSO the password doesn't go anywhere near Bitwarden, and instead to your IdP.

**Comment by pa-jberanek** [comment] 2022-08-22 13:42
(By the way, SSO login with the 'bw' CLI works fine, it's just that the Terraform provider expects to always use the CLI to login, and not rely upon a previous, successful login (which creates the session token)).

**Comment by pa-jberanek** [comment] 2022-08-22 13:46
![image](https://user-images.githubusercontent.com/22837936/185936344-170b5d4b-e466-4fd7-8daf-2128f6774939.png)

**Comment by pa-jberanek** [comment] 2022-08-22 13:54
However, on my part I've confused a Bitwarden "Organization API key" with a "Personal API key"... https://bitwarden.com/help/personal-api-key/

So, potentially that API key method is an option, albeit one that requires each user to do more work.

**Comment by pa-jberanek** [comment] 2022-08-22 13:58
On second thought, the problem with the API key method is that each user has to access their API key **and then keep it secret as they pass it to the provider**. I know people will just end up doing things like shoving the details in their bash/Powershell profile :(

**Comment by maxlaverse** [comment] 2022-08-22 19:26
> the problem with the API key method is that each user has to access their API key and then keep it secret as they pass it to the provider.

To rephrase, the goal is to have a shared Terraform projects set up in a way that requires passing a Bitwarden session in order to prevent engineers from thinking about using a personal API key and eventually hard-coding, is that correct ?

I don't have a Bitwarden organization myself. Any chance to set up policies on API keys and require a periodic rotation ?

> However, on my part I've confused a Bitwarden "Organization API key" with a "Personal API key".

I'll clarify the documentation.

**Comment by maxlaverse** [comment] 2022-08-22 19:45
Do you need the Vault's password when you authenticate with SSO, or is it unlocked at first @pa-jberanek ?

**Comment by pa-jberanek** [comment] 2022-09-05 11:27
> Do you need the Vault's password when you authenticate with SSO, or is it unlocked at first @pa-jberanek ?

My enterprise trial is now disabled so I can't check again, but I believe the master password is only requested on unlock.

**Comment by maxlaverse** [comment] 2022-09-09 17:03
Will you buy an enterprise license ?

**Comment by maxlaverse** [comment] 2022-09-16 17:26
I'm happy to build the feature it, but we need at least a couple of users wanting it. No matter your answer, this issue lead at least to have the authentication refactored which would make implementing this feature much easier.

**Comment by pa-jberanek** [comment] 2022-09-22 08:14
> Will you buy an enterprise license ?

We will soon have enterprise licenses for our company.

**Comment by maxlaverse** [comment] 2022-09-28 20:19
When you have time, could you try out this branch https://github.com/maxlaverse/terraform-provider-bitwarden/pull/49  ?

The following steps should allow you to use this custom version of the provider:
* prepare a Terraform repository that uses the latest version of the Bitwarden provider
* when you run `terraform init`, the provider's binary will be downloaded. Try to locate them, e.g. in`.terraform/providers/registry.terraform.io/maxlaverse/bitwarden/0.2.0/darwin_amd64/terraform-provider-bitwarden_v0.2.0`
* checkout the branch and build a binary for your platform, e.g. `GOOS=darwin  GOARCH=amd64 go build`
* replace the downloaded provider with your custom version
* in `.terraform.lock.hcl`, remove the `hashes` field for the "registry.terraform.io/maxlaverse/bitwarden" provider

**Comment by pa-jberanek** [comment] 2022-10-03 16:47
We now have our Enterprise seats, so will attempt the above testing when I get some time. I am unfortunately struggling with some issues with using the Bitwarden CLI to do SSO logins on headless Linux consoles

**Comment by pa-jberanek** [comment] 2022-10-03 16:59
OK, so - given

```
$ cat provider.tf
provider "bitwarden" {
  server          = "https://vault.bitwarden.com"
  email           = "test@laverse.net"
  master_password = var.bw_master_password
  session_key     = var.bw_session_key
}

terraform {
  required_providers {
    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = ">= 0.1.1"
    }
  }
  required_version = ">= 1.0.2"
}
```

I get
```
$ terraform plan
â·
â Error: error running '/usr/local/bin/bw login test@laverse.net --raw --passwordenv BW_PASSWORD': exit status 1, Username or password is incorrect. Try again.
â
â   with provider["registry.terraform.io/maxlaverse/bitwarden"],
â   on provider.tf line 1, in provider "bitwarden":
â    1: provider "bitwarden" {
â
âµ
```

**Comment by pa-jberanek** [comment] 2022-10-03 17:01
With a session key, no email address is required, and it seems the provider is still attempting a login, rather than just using the session?

**Comment by pa-jberanek** [comment] 2022-10-03 17:18
Possibly of use:
![image](https://user-images.githubusercontent.com/22837936/193639026-d9094df8-b44c-45d0-8671-8a731183bb15.png)

**Comment by maxlaverse** [comment] 2022-10-08 14:07
> I get

You really had tried with my email ?

> With a session key, no email address is required, and it seems the provider is still attempting a login, rather than just using the session?

Yes, technically the email is not required to interact with Bitwarden when you have a session key. I use it to be sure you're connected to the right Vault, since the cached Vault might be a different one depending on the provider's input.

> OK, so - given

Just to clear any confusion: you also followed those [steps](https://github.com/maxlaverse/terraform-provider-bitwarden/issues/42#issuecomment-1261421991) to try out the following branch https://github.com/maxlaverse/terraform-provider-bitwarden/pull/49 ?

**Comment by maxlaverse** [comment] 2022-10-26 18:14
Experimental support released in [v0.3.0](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.3.0)

**Closed by maxlaverse** 2022-10-26 18:14 UTC

**Comment by zoechi** [comment] 2022-11-07 11:16
> Yes, technically the email is not required to interact with Bitwarden when you have a session key. I use it to be sure you're connected to the right Vault, since the cached Vault might be a different one depending on the provider's input.

It still asks the `master_password`, this is what I'd rather avoid passing around. 

Any idea what might be wrong?

My attempt to get the gitlab-access-token out of Bitwarden:

```tf
terraform {
  required_providers {
    gitlab = {
      source  = "gitlabhq/gitlab"
      version = "3.18.0"
    }

    bitwarden = {
      source  = "maxlaverse/bitwarden"
      version = "0.3.0"
    }
  }
}

data "bitwarden_item_login" "gitlab-access-token" {
  id = "d51b858b-6a21-4799-8e37-df46008b70a4"
}

provider "gitlab" {
  token = data.bitwarden_item_login.gitlab-access-token.password
}

provider "bitwarden" {
  session_key = var.bw_session_key
  email       = "guenter@gzoechbauer.com"
  # server      = "https://vault.bitwarden.com"
}

variable "bw_session_key" {
  type        = string
  description = "Bitwarden session key of the currently logged in session"
  sensitive   = true
}

# Add a project owned by the user
resource "gitlab_project" "cloud-gitlab-repos" {
  name               = "cloud-gitlab-repos"
  namespace_id       = 123
}
```

**Comment by maxlaverse** [comment] 2022-11-07 18:33
Hi @zoechi !
Indeed, the `master_password` was still required by the configuration. I opened a PR to make it optional but I need to check it once more tomorrow or later before releasing it: https://github.com/maxlaverse/terraform-provider-bitwarden/pull/53

**Comment by zoechi** [comment] 2022-11-08 04:50
Hi @maxlaverse thanks a lot for looking into it and your quick response 🚀👍

**Comment by maxlaverse** [comment] 2022-11-08 20:23
Released the change in [v0.3.1](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.3.1). Happy to hear any feedback @zoechi.

**Comment by zoechi** [comment] 2022-11-09 09:53
@maxlaverse I get "Error: not enough parameters provided to login"
It seems `LoginMethodNone` needs to be handled at https://github.com/maxlaverse/terraform-provider-bitwarden/pull/53/files#diff-58d6a027753b50994deb7e11e4a99dde423f35844986019bd9cea5e0c94aba22L155

**Comment by maxlaverse** [comment] 2022-11-09 10:47
`LoginMethodNone` means that the provider can't login because you didn't provide all the information it requires. That's the case here if you haven't given it the master password parameter, so I think it's working as intended (I'll need to improve this error message and explain this).

The real question is: why does the provider need to login since you gave it a session key.

Can you try running the following in your Terraform workspace:
```bash
BITWARDENCLI_APPDATA_DIR=.bitwarden bw status
```

And then:
```bash
BW_SESSION="<session_key_your_gave_this_provider>" " BITWARDENCLI_APPDATA_DIR=.bitwarden bw status
```

**Comment by zoechi** [comment] 2022-11-10 12:33
```json
{"serverUrl":null,"lastSync":"2022-11-10T12:31:10.422Z","userEmail":"user@example.com","userId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","status":"unlocked"}
```

**Comment by maxlaverse** [comment] 2022-11-10 13:40
The serverUrl is null which I didn't think could happen. That's probably the case when you use bitwarden.com. As a result, logoutIfIdentityChanged doesn't early exits and sets the status as logged out. I can look that up in the next days

**Comment by maxlaverse** [comment] 2022-11-22 19:19
I changed a couple of things around the session keys in [v0.3.2](https://github.com/maxlaverse/terraform-provider-bitwarden/releases/tag/v0.3.2). I hope my tests cover the problem you were facing and addresses it. I was able to use a session key to authenticate against the official Bitwarden servers.

I still need to improve the documentation. Just in case you didn't know, you have to specific the right Vault path when generating the session key, or set the `vault_path` parameter in the provider:
```
BITWARDENCLI_APPDATA_DIR=.bitwarden bw login
```

Again, happy to hear any feedback @zoechi. I'm preparing a small release 0.3.3 to fix an error message.

**Comment by zoechi** [comment] 2022-12-04 16:40
I wasn't able to get back to the task yet. Thank's a lot for looking into it. I'll report back as soon as I know more :+1:

**Comment by jollyroger** [comment] 2023-08-01 23:55
Hi @maxlaverse. Thank you for all the hard work!

Sorry to bring this back, but with provider version `v0.6.1` the issue is still somehow present. 

As was highlighted earlier, the `email` attribute is still required so you cannot omit it. Also, when trying to provide just server, email and session_key attributes, Terraform throws these errors

```hcl
provider "bitwarden" {
  server          = var.bw_server
  email           = var.bw_user_email
  session_key     = var.bw_session
}
```

```
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on bitwarden.tf line 48, in provider "bitwarden":
│   48: provider "bitwarden" {
│ 
│ "client_id": all of `client_id,client_secret,master_password` must be specified
╵
╷
│ Error: Missing required argument
│ 
│   with provider["registry.terraform.io/maxlaverse/bitwarden"],
│   on bitwarden.tf line 48, in provider "bitwarden":
│   48: provider "bitwarden" {
│ 
│ "client_secret": all of `client_id,client_secret,master_password` must be specified
```

Finally, according to the bw CLI documentation, there are already some environment variables like `BW_CLIENTID`. `BW_CLIENTSECRET` and `BW_SESSION` that could be reused instead of defining separate `TF_VAR_xxx` variables. Please let me know if a separate ticket needs to be raised for this.

**Comment by maxlaverse** [comment] 2023-08-03 12:04
Hi @jollyroger !
Are you sure your 3 variables actually have a content ?

There is a test in this project with this configuration and it's green (doesn't mean it can't be wrong).
Also, trying the following fails on an authentication error, meaning the combination of parameters passed the verification:
```terraform
provider "bitwarden" {
  server          = "something"
  email           = "something"
  session_key     = "something"
}

terraform {
  required_providers {
    bitwarden = {
      source  = "maxlaverse/bitwarden"
    }
  }
}

resource "bitwarden_folder" "cloud_credentials" {
  name = "My Cloud Credentials"
}
```

giving:
```
Planning failed. Terraform encountered an error while generating this plan.
│ Error: unable to unlock Vault with provided session key (status: unauthenticated)
`

**Comment by maxlaverse** [comment] 2023-08-07 16:08
@jollyroger

The _session key_  needs to be for the Vault used by your workspace. If you don't set the `BITWARDENCLI_APPDATA_DIR` environment variable when unlocking your Vault, the key will be valid for the Vault in the default path of your operation system. Your workspace Vault however, is stored under the `.bitwarden` folder of your workspace. 

This leaves you with two options.
1. Set `vault_path` to the path of your local Vault instead of the workspace's one
2. Set the `BITWARDENCLI_APPDATA_DIR=.bitwarden` before trying to get a session key 

If this doesn't work, can you try hard-coding your session key in your `*.tf` file (just for testing) ? That's the best way to rule out and misconfiguration.

**Comment by maxlaverse** [comment] 2023-08-10 06:22
> Finally, according to the bw CLI documentation, there are already some environment variables like BW_CLIENTID. BW_CLIENTSECRET and BW_SESSION that could be reused instead of defining separate TF_VAR_xxx variables. Please let me know if a separate ticket needs to be raised for this.

@jollyroger btw, you should already be able to use those Bitwarden documented environment variables.

I'd like to improve the documentation around user-provided session keys since it seems to be used. Could you let me know if you got it to work with my [previous indications](https://github.com/maxlaverse/terraform-provider-bitwarden/issues/42#issuecomment-1668165628) ?. Also, I'm curious about your use-case: why did you want to perform the authentication outside of the provider ?

**Comment by jollyroger** [comment] 2023-08-28 21:10
Thank you @maxlaverse I finally found a solution for me.

I'd like to leave some minimal working code for anyone trying to share bw context between the `bw` cli tool and Terraform provider (Terraform required version: v1.5 due to `pathexpand` function being used). Please note that the `bitwarden` GUI and the `bw` CLI tools have different ..._APPDATA_DIR folders so please make sure you are using the correct one (e.g. `~/.config/Bitwarden CLI`)

 ### Login to Vault and set necessary variables

```bash
export BW_SESSION=$(bw unlock --raw)
```

### Use this provider configuration:

```hcl
variable "bw_server" {
  description = "Bitwarden Server URL"
  type        = string
  default     = "https://vault.bitwarden.com"
}

variable "bw_vault_path" {
  description = "Bitwarden CLI APP Vault Path"
  type        = string
  default     = null
}

variable "bw_user_email" {
  description = "User Email used to log in Bitwarden Server"
  type        = string
}

provider "bitwarden" {
  server          = var.bw_server
  email           = var.bw_user_email
  vault_path      = try(pathexpand(var.bw_vault_path), pathexpand("~/.config/Bitwarden CLI"))
}
```
